name: global keyboard handler

on:
    issues:
        types: [opened]

permissions:
    contents: write

jobs:
    pieceofshit:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v4
            - name: get lua
              uses: ljmf00/setup-lua@v1.0.0
              with:
                lua-version: "5.3"
                install-luarocks: "true"
            - name: installeth deps
              run: |
                  deps=$(cat hTxt/luaDeps.txt)
                  for d in $deps; do luarocks install --local "$d"; done
                  eval "$(luarocks path --bin)"
            - name: runeth
              run: |
                  issNodeId=$(curl -s "https://api.github.com/repos/RixInGithub/RixInGithub/issues/${{ github.event.issue.number }}" | jq -r ".node_id")
                  lua hTxt/processKbd.lua $issNodeId "${{ github.event.issue.title }}" "${{ github.event.issue.user.login }}"
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "@${{ github.event.issue.user.login }} pressed a key"
                  git push